/**
 * WelcomeHtmlBoxChunk
 *
 * WelcomeHtmlBox chunk example
 *
 * @author    Nicola Lambathakis http://www.tattoocms.it/
 * @category	chunk
 * @version    3.1 RC
 * @internal @modx_category Dashboard
 */
<div class="alert alert-success">
<p>The content of this Widget is taken from <a href="index.php?a=76"><b>WelcomeHtmlBoxChunk</b></a> chunk. </p>
</div>
<p><b>MODx Tags</b> give you a simple, powerful way to include more variable content into your web pages.</p>

<p>Tags are replaced with the content they output. Here are a few examples:</p>

<table class="table-responsive table-striped table-hover table-bordered">
<tbody>
<tr>
<th>Tag</th>
<th>Description</th>
</tr>

<tr>
<td>&#91;&#91;snippet&#93;&#93;</td>
<td>for caching snippets. Inserts the output of a snippet named 'snippet' into your page</td>
</tr>

<tr>
<td>&#91;!snippet!&#93;</td>
<td>for non-caching snippets. Inserts the output of a snippet named 'snippet' into your page.</td>
</tr>

<tr>
<td>&#91;(setting)&#93;</td>
<td>Inserts the value of a site-wide setting named 'setting' into your page.</td>
</tr>

<tr>
<td>&#91;*resourceField/TV*&#93;</td>
<td>Inserts various blocks of content specific to the page being displayed.</td>
</tr>

<tr>
<td>&#91;^timing^&#93;</td>
<td>Shows how long it took to create the current page.</td>
</tr>

<tr>
<td>&#91;~link~&#93;</td>
<td>Makes a link to another document in your MODx site.</td>
</tr>

<tr>
<td><br />
{{chunk}}</td>
<td>Inserts a chunk of HTML into your page.</td>
</tr>

<tr>
<td>&#91;+placeholder+&#93;</td>
<td>Acts as a placeholder for content generated by a snippet. Usually used in a chunk specified in an argument of the snippet to format the snippet's output.</td>
</tr>
</tbody>
</table>